# Generated by 'nixos-generate-config' — modified to add NPU and microcode.
# Regenerating will overwrite customizations; merge changes back manually.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8a336b9c-8e1f-4c75-b921-632c807f91d9";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@nixos_root" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/D365-D156";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a336b9c-8e1f-4c75-b921-632c807f91d9";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8a336b9c-8e1f-4c75-b921-632c807f91d9";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/8a336b9c-8e1f-4c75-b921-632c807f91d9";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8a336b9c-8e1f-4c75-b921-632c807f91d9";
      fsType = "btrfs";
      options = [ "noatime" "subvol=@swap" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
