# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/94ea8082-45b3-41e4-bfa0-7e51b02f1d91";
      fsType = "btrfs";
      options = [ "subvol=@nixos_root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/94ea8082-45b3-41e4-bfa0-7e51b02f1d91";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/94ea8082-45b3-41e4-bfa0-7e51b02f1d91";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/94ea8082-45b3-41e4-bfa0-7e51b02f1d91";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/94ea8082-45b3-41e4-bfa0-7e51b02f1d91";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/6776-1721";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
